export const blogCategories = [
  "Frontend Development",
  "Backend Development",
  "Full-Stack Development",
  "Graphics Design",
  "3d Design",
  "UI/UX Design",
  "Motion Graphics",
  "Game Developing",
  "UnReal engine",
  "Netwrorking",
  "C",
  "C++",
  "Python",
  "ICT-11",
  "Database Management",
  "DevOps & Deployment",
  "API Development",
  "Web Security",
  "Performance Optimization",
  "Testing & Debugging",
  "Mobile Responsive Design",
  "SEO & Web Analytics",
  "Content Management Systems (CMS)",
  "E-commerce Development",
  "Web3 & Blockchain Development",
];
